name: firebase_implementation
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  intl: ^0.20.2
  gap: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/app_icon.png'
  adaptive_icon_forground: 'assets/ic_launcher.png'
  adaptive_icon_background: '#ffffff'
  flutter_lints: ^5.0.0


assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  
  
  
  






flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
