// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi_3aDsszgrxeoXdLWAjixWtc2o3xTan4',
    appId: '1:1037218987151:web:ba8bf1ded286c028e784fa',
    messagingSenderId: '1037218987151',
    projectId: 'firebaseimpl',
    authDomain: 'fir-impl-b63ff.firebaseapp.com',
    storageBucket: 'firebaseimpl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUrk1zMOiKC-QQOlFO_30EzLwXFnOKxk',
    appId: '1:1037218987151:android:a976e8d6e8f0d4e8e784fa',
    messagingSenderId: '1037218987151',
    projectId: 'firebaseimpl',
    storageBucket: 'firebaseimpl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjVEckW6la8Cq7MzQJkCWJhpWc9WdGtH8',
    appId: '1:1037218987151:ios:b3fcd6dbfe10f39fe784fa',
    messagingSenderId: '1037218987151',
    projectId: 'firebaseimpl',
    storageBucket: 'firebaseimpl.firebasestorage.app',
    iosBundleId: 'com.example.firebaseImplementation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjVEckW6la8Cq7MzQJkCWJhpWc9WdGtH8',
    appId: '1:1037218987151:ios:b3fcd6dbfe10f39fe784fa',
    messagingSenderId: '1037218987151',
    projectId: 'firebaseimpl',
    storageBucket: 'firebaseimpl.firebasestorage.app',
    iosBundleId: 'com.example.firebaseImplementation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi_3aDsszgrxeoXdLWAjixWtc2o3xTan4',
    appId: '1:1037218987151:web:994356acb6e6a74ee784fa',
    messagingSenderId: '1037218987151',
    projectId: 'firebaseimpl',
    authDomain: 'fir-impl-b63ff.firebaseapp.com',
    storageBucket: 'firebaseimpl.firebasestorage.app',
  );
}
